1. Load the CSV dataset

In [8]:
import pandas as pd
data = pd.read_csv("students.csv")
print(data)

Empty DataFrame
Columns: [Hello! I am,  Shreya Rastogi from India.]
Index: []

2. Display dataset summary (info() & describe())

In [11]:
data.info()
data.describe()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 2 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Hello! I am                  0 non-null      object
 1    Shreya Rastogi from India.  0 non-null      object
dtypes: object(2)
memory usage: 132.0+ bytes

       Hello! I am  Shreya Rastogi from India.
count            0                           0
unique           0                           0
top            NaN                         NaN
freq           NaN                         NaN

3. Filter students scoring above 80

In [17]:
import pandas as pd

data = pd.DataFrame({
    "Name": ["Aman", "Rahul", "Shreya"],
    "Marks": [75, 85, 90],
    "Subjects": ["maths","English","Science"]
})
data[data["Marks"] > 80]

     Name  Marks Subjects
1   Rahul     85  English
2  Shreya     90  Science

4. Sort students by marks (highest first)

In [20]:
data.sort_values(by="Marks", ascending=False)

     Name  Marks Subjects
2  Shreya     90  Science
1   Rahul     85  English
0    Aman     75    maths

5. Count students per subject

In [23]:
data["Subjects"].value_counts()

Subjects
maths      1
English    1
Science    1
Name: count, dtype: int64

6. Fill missing marks with mean

In [ ]:
import pandas as pd
data = pd.DataFrame({
    "Name": ["Aman", "Rahul", "Shreya"],
    "Marks": [80, None, 90]
})
data["Marks"] = data["Marks"].fillna(data["Marks"].mean())
print(data)

     Name  Marks
0    Aman   80.0
1   Rahul   85.0
2  Shreya   90.0

7. Group data by subject & average marks

In [ ]:
import pandas as pd

data = pd.DataFrame({
    "Name": ["Aman", "Rahul", "Shreya"],
    "Subject": ["Math", "Math", "Science"],
    "Marks": [80, 90, 85]
})
print(data.groupby("Subject")["Marks"].mean())

Subject
Math       85.0
Science    85.0
Name: Marks, dtype: float64

8. Save cleaned dataset to CSV

In [30]:
data.to_csv("clean_students.csv", index=False)